name: dio_firebase_performance
description: A new Flutter package project.
version: 0.4.0
homepage: https://github.com/abdoosaed/dio_firebase_performance_plus

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ">=4.0.0 <5.0.0"
  firebase_performance: ">=0.0.0 <1.0.0"

flutter: